const express=require('express'),cors=require('cors'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');require('dotenv').config();
const app=express();app.set('trust proxy',1);app.disable('x-powered-by');
const hits={};app.use((req,res,next)=>{if(req.path==='/api/health'||req.path==='/')return next();let ip=req.ip||'x';if(!hits[ip])hits[ip]={c:0,t:Date.now()};if(Date.now()-hits[ip].t>60000)hits[ip]={c:0,t:Date.now()};hits[ip].c++;if(hits[ip].c>200)return res.status(429).json({error:"Too many"});next();});
const MONGO_URI=process.env.MONGO_URI||process.env.MONGODB_URI||"";mongoose.connect(MONGO_URI,{dbName:"genzvisual"}).then(()=>{console.log("Mongo OK");ensureAdmins();});
const userSchema=new mongoose.Schema({email:{type:String,unique:true,lowercase:true},password:String,role:{type:String,enum:['reader','creator','admin'],default:'reader'},name:String,portfolio:String,bio:String,upiId:{type:String,default:''},createdAt:{type:Date,default:Date.now}});
const User=mongoose.models.User||mongoose.model('User',userSchema);
const novelSchema=new mongoose.Schema({title:String,author:String,genre:String,description:String,cover:String,coverImage:String,content:String,type:String,creatorEmail:String,creatorName:String,chapters:Array,access:{type:String,enum:['free','paid'],default:'free'},price:{type:Number,default:0},authorUpi:{type:String,default:''}},{strict:false,timestamps:true});
const Novel=mongoose.models.Novel||mongoose.model('Novel',novelSchema);
const comicSchema=new mongoose.Schema({title:String,author:String,description:String,cover:String,coverImage:String,pages:Array,type:String,creatorEmail:String,creatorName:String,access:{type:String,enum:['free','paid'],default:'free'},price:{type:Number,default:0},authorUpi:{type:String,default:''}},{strict:false,timestamps:true});
const Comic=mongoose.models.Comic||mongoose.model('Comic',comicSchema);
app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:"50mb"}));
const ADMINS=[{email:"xhettriakash1@gmail.com",password:"Akash123",name:"Akash Main"},{email:"akashchettri2003@gmail.com",password:"Akashchettri2003",name:"Akash Second"}];
async function ensureAdmins(){for(let a of ADMINS){if(!await User.findOne({email:a.email})){let h=await bcrypt.hash(a.password,10);await User.create({email:a.email.toLowerCase(),password:h,role:'admin',name:a.name});}else await User.updateOne({email:a.email},{role:'admin'});}}
const JWT=process.env.JWT_SECRET||"GENZ_SECRET_2026_SECURE";
const protect=(req,res,next)=>{try{let t=req.headers.authorization?.split(" ")[1];if(!t)return res.status(401).json({error:"Login"});req.user=jwt.verify(t,JWT);next();}catch{res.status(401).json({error:"Invalid"});}};
const isAdmin=(req,res,next)=>{if(req.user.role!=='admin')return res.status(403).json({error:"Admin only"});next();};
app.get('/api/health',(req,res)=>res.json({ok:true,v:"v704.5"}));app.get('/',(req,res)=>res.send("🟢 v704.5 LIVE + UPI"));
async function loginHandler(req,res){let {email,password}=req.body;let u=await User.findOne({email:email.toLowerCase()});if(!u)return res.status(401).json({error:"Not Found"});if(!await bcrypt.compare(password,u.password))return res.status(401).json({error:"Wrong"});let token=jwt.sign({id:u._id,email:u.email,role:u.role},JWT,{expiresIn:"7d"});res.json({success:true,token,user:{email:u.email,role:u.role,name:u.name,id:u._id,upiId:u.upiId||''}});}
app.post('/api/login',loginHandler);app.post('/api/auth/login',loginHandler);
async function regHandler(req,res){let {email,password,name,role,code}=req.body;if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({error:"Exists"});let isAdm=ADMINS.some(a=>a.email===email.toLowerCase());let newRole=isAdm?'admin':(role==='creator'?'creator':'reader');if(role==='creator'&&code&&code!=='CREATOR2026'&&!isAdm)return res.status(403).json({error:"Wrong code"});let h=await bcrypt.hash(password,10);await User.create({email:email.toLowerCase(),password:h,role:newRole,name:name||"User"});res.json({success:true,msg:newRole});}
app.post('/api/auth/register',regHandler);app.post('/api/auth/register-creator',regHandler);app.post('/api/register',regHandler);app.post('/api/register-creator',regHandler);
app.get('/api/users',protect,isAdmin,async(req,res)=>res.json(await User.find().select('-password').sort({createdAt:-1})));
app.get('/api/novels',async(req,res)=>res.json(await Novel.find().sort({createdAt:-1}).limit(200)));
app.get('/api/novels/:id',async(req,res)=>{ try{ let n=await Novel.findById(req.params.id); if(!n) return res.status(404).json({error:"Not found"}); res.json(n); }catch{res.status(404).json({error:"Invalid ID"})} });
app.post('/api/novels',protect,async(req,res)=>{let me=await User.findOne({email:req.user.email});let n=await Novel.create({...req.body,type:'novel',creatorEmail:req.user.email,creatorName:req.user.email,access:(req.body.access||req.body.accessType||'free'),price:req.body.price||0,authorUpi:me?.upiId||''});res.json({ok:true,novel:n});});
app.get('/api/comics',async(req,res)=>res.json(await Comic.find().sort({createdAt:-1}).limit(200)));
app.get('/api/comics/:id',async(req,res)=>{ try{ let c=await Comic.findById(req.params.id); if(!c) return res.status(404).json({error:"Not found"}); res.json(c); }catch{res.status(404).json({error:"Invalid ID"})} });
app.post('/api/comics',protect,async(req,res)=>{let me=await User.findOne({email:req.user.email});let c=await Comic.create({...req.body,type:'comic',creatorEmail:req.user.email,creatorName:req.user.email,cover:req.body.cover||req.body.coverImage||(req.body.pages&&req.body.pages[0]),access:(req.body.access||req.body.accessType||'free'),price:req.body.price||0,authorUpi:me?.upiId||''});res.json({ok:true,comic:c});});
app.get('/api/books',async(req,res)=>{let n=await Novel.find().sort({createdAt:-1}).limit(100);let c=await Comic.find().sort({createdAt:-1}).limit(100);res.json([...n,...c]);});
app.get('/api/can-read/:id',protect,async(req,res)=>{let b=await Novel.findById(req.params.id)||await Comic.findById(req.params.id);if(!b)return res.status(404).json({error:"Not found"});if(b.access==='free'||!b.access)return res.json({canRead:true});if(req.user.role==='admin')return res.json({canRead:true});if(b.creatorEmail===req.user.email)return res.json({canRead:true});res.json({canRead:false,price:b.price||0,authorUpi:b.authorUpi||''});});
app.post('/api/save-upi',protect,async(req,res)=>{let upi=(req.body.upiId||'').trim();if(!upi.includes('@'))return res.status(400).json({error:"Invalid UPI"});await User.updateOne({email:req.user.email},{upiId:upi});res.json({ok:true,upiId:upi});});
app.get('/api/me',protect,async(req,res)=>{let u=await User.findOne({email:req.user.email}).select('-password');res.json(u);});
app.post('/api/fix-upi-all',protect,async(req,res)=>{let me=await User.findOne({email:req.user.email});if(!me?.upiId)return res.status(400).json({error:"Save UPI first"});await Novel.updateMany({creatorEmail:req.user.email},{authorUpi:me.upiId});await Comic.updateMany({creatorEmail:req.user.email},{authorUpi:me.upiId});res.json({ok:true,upiId:me.upiId});});
app.delete('/api/novels/:id',protect,isAdmin,async(req,res)=>{await Novel.findByIdAndDelete(req.params.id);res.json({ok:true});});
app.delete('/api/comics/:id',protect,isAdmin,async(req,res)=>{await Comic.findByIdAndDelete(req.params.id);res.json({ok:true});});
const PORT=process.env.PORT||10000;app.listen(PORT,()=>console.log("✅ v704.5 LIVE "+PORT));
